[package]
name = "rust-web-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "gzip"] }
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
colored = "3.0"
serde_json = "1.0"